### PR TITLE
Enable periodic hostname resolution

### LINKED ISSUE #45: :telemetry.execute blocks the calling process until UDP is sent
Hi,

I have noticed that when using `telemetry_metrics_statsd` invoking `:telemetry.execute` is blocking the calling process until the metric is send over UDP. That was a bit surprising, as I thought the library would forward all the events to `TelemetryMetricsStatsd` process that would send things over UDP itself? 

Is that an intentional design decision? While UDP sending is usually pretty fast, it can sometimes block up (especially when resolving DNS names and especially in K8s/docker environment) and that means the caller is being delayed by the metrics for quite a significant time. I'd like to change this and the easiest would be to modify this library to instead have a background process send metrics over UDP, rather than the caller. Please let me know if you agree with this approach however. :)

### PR DESCRIPTION
**Pull request by haljin**
Resolves #45  (at least partially)

- Make `TelemetryMetricsStatsd` optionally resolve the hostname of the Statsd server on startup and then again on a specified interval
- Allows for dynamic reconfiguration of the host/port of the reporter
- Additionally optionally allows for naming of the ETS pool allowing for more reporters to be started at the same time without name conflicts

### CODE REVIEW

**Comment by haljin** [comment]
The check is failing due to an optional dependency between `:meck` and `:hamcrest` - it seems the older Dialyzer does not figure out that this is not being used here. I guess the solution is to ignore that warning? I don't really know how else to test this feature without using `mock` :).

**Comment by arkgil** [comment]
Thanks @haljin, periodic DNS resolution looks like a great way forward! I'd remove the function to update the hostname manually for now.

Would you be able to test how this improves performance in your system before we merge?

**Comment by haljin** [comment]
I've tried it now and I can see quite a big difference, e.g.:

image

exec_time is time reported by Redis itself, while transaction_time includes client time + sending 3-4 metrics to StatsD. Considering it's only a couple a drop of 2 ms on average is quite significant. I'm also assuming the metrics will be less spiky now too, however to fully validate it I'd have to update all the services to make sure all metrics sent by everyone are using IPs.

Another service that calls this one can also see it respond much faster (about 25% improvement)

image

**Comment by arkgil** [comment]
Thanks @haljin, this looks very promising!

**Comment by epilgrim** [comment]
This PR is incredible!! I had this situation where I couldn't send ecto telemetry, because it was slowing everything down. I thought it was because of the single genserver, so I sent the PR for using a pool. It didn't fix the issue.
I stopped digging there, but honestly never thought about the DNS resolution as being the culprit.
Now, It's been 15 minutes running this PR in production... and the slowness doesn't seem to appear anymore.

Kudos @haljin!! this is awesome

**Comment by arkgil** [comment]
@epilgrim thanks for posting this! Thanks @haljin! 🙏

**Pull request merged**
